[#7] 주문, 결제 기능 개발
f-lab-edu/just-10-minutes pull request #13
Opened 2024-08-10 08:59 UTC by corea1836

2024-08-10 11:23 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +import static com.flab.just_10_minutes.Util.Config.IamportConfig.iamportClient;
## iamport 비인증 결제(api 결제)에 대한 안내 입니다.
1. iamport 클라이언트를 사용하기 위해 발급받은 impKey, impSecretKey를 사용해 auth token을 발급 받습니다.
iamportClient는 토큰을 발급 받은 객체를 제공합니다.

2024-08-10 11:28 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            billingKey = fetchBillingKey(paymentDataDto);
2. iamport는 상점(각 서비스를 얘기하는 것 같음)마다 중복되지 않는 키와 카드 정보를 이용해 iamport 서버에 결제 정보를 저장합니다.
이 후 결제 정보를 이용해 api 결제를 진행할 수 있습니다.
just-10-minutes 서비스의 고객 아이디와 중복되지 않는 키(bliingKey)를 1:1로 매칭 했습니다.

2024-08-10 11:30 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +        return billingKey;
just-10-minutes의 아이디와 iamport에서 결제하기 위한 customUid는 1:1로 관리 됩니다.
customUid라는 용어는 iamport에서 사용하는 용어로 서비스에서는 편의를 위해 billingKey로 변경해서 사용합니다.

2024-08-10 11:33 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            paymentResult = PaymentResult.from(iamportClient.againPayment(PaymentDataDto.toPaymentData(paymentDataDto, billingKey)).getResponse());
3. 발급받은 billingKey를 사용해 결제 요청을 합니다.
iamportClient의 againPayment(일회성 결제) 메서드를 사용하며 IamportResponse<Payment> 객체를 반환 합니다.
반환받은 객체는 결제 정보를 담고 있으며 just-10-minutes에서 PaymentResult 객채로 매핑해 사용합니다.

2024-08-10 11:35 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +        }
결제 결과 status는 paid, cancelled, fail 로 구분되는것 같습니다.
결과에 따른 추가적인 작업이 필요할 수도 있다고 생각됩니다.
(블랙박스)

2024-08-10 11:37 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +    private String pg;
pg는 고객사가 열어놓은(?) 결제사(?) 인 것 같습니다.
필수값이며, 비인증 결제를 제공하는 결제사가 많지 않아 나이스페이먼트로 연결했습니다.

2024-08-10 11:40 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
## 질문
access token 가지고 있는 iamportClient는 Iamport와 통신할 수 있는 객체 입니다.
access token의 경우 하루의 유효기간을 가지고 있는데, 어떻게 갱신해야할까요?

2024-08-10 11:41 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +                                .pwd_2Digit("")
결제 정보가 실제 카드 정보가 필요한데, 제 개인 카드 정보를 올릴 수가 없어 공란 처리 후 올렸습니다.

2024-08-10 11:43 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
## 질문
주문, 결제 테스트는 외부 연동이 있는 로직이다보니 테스트 코드를 어떻게 나눠야 할지 감이 오지 않습니다.
또한 예외가 발생할 수 있는데, 이 예외를 어떻게 발생시켜 테스트를 할지도 모르겠습니다.

따라서 성공하는 로직에 대한 테스트만 진행 했습니다.
지금은 고정된 주문 가격을 iamport를 통해 결제 후 저장하는 로직에 대한 테스트 입니다.
추후 재고차감, 포인트 차감 후 최종 가격 계산 로직을 더해 최종 결제 로직을 만들 예정 입니다.

2024-08-10 11:47 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/service/OrderService.java
> +                                                                                        .billingData(orderDto.getBillingData())
## 질문
클래스 내부로 생성 로직을 빼기 애매한 것들은 서비스 로직에 포함 되도 괜찮을까요?
이 댓글 위, 아래에 있는 객체인 PaymentResult, Order 모두 복수의 객체를 참조해 자신을 생성 합니다.
생성자로 빼자니 빌더의 장점(명확한 매핑 관계 확인)을 잃는것 같고 빌더로 서비스로직에 넣으니 지저분해보이는 단점이 있네요.

2024-08-10 11:49 UTC, corea1836 commented on src/main/resources/application.properties
> +payment.iamport.imp_secret=M11mpNrYutDR7gnIv8Sg6bPJ3IIoLSnKs49Z80SZxdPJoNSgQUUIjFuVB2MAKU69zPpfP0kyCODCtLRf
## 질문
이런 설정 파일은 숨겨야 할까요?
서비스 내부에서 사용하고 있는 키, 서버ip port정보 등은 숨겨야 한다고 하던데 원격 서버에 동적으로 주입해주는 서비스나 프로그램이 따로 있나요?

2024-08-10 11:56 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +public class PaymentGateWay {
사실 비지니스 계층을 담고있는 서비스 레이어지만, 다른 도메인(ex. 주문)에서 일방향 참조만 한다는 뜻에서 GateWay라는 용어를 사용 했습니다.

2024-08-10 11:57 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
iamportd에서 사용하는 용어는 직관적이지 않아 서비스에 맞게 매핑해서 사용합니다.
- impUid -> paymentTxId
- merchantUid -> orderId

2024-08-10 11:59 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
## 피드백 부탁드려요.
iamport의 Payment객체의 필드는 더 많은데, 이번 프로젝트에서 사용할만한 필드만 따로 빼내어 매핑 했습니다.
주로 주문, 주문취소, 실패에 관한 필드만 따로 뺐습니다.
이정도만 사용해도 무방할까요?(빼서 찜찜한 필드 : 결제 정보[카드사, 카드번호, 등등])

2024-08-10 12:00 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +    public static PaymentResult from(Payment iamportPayment) {
## 피드백 부탁드려요.
iamport의 Payment객체의 필드는 더 많은데, 이번 프로젝트에서 사용할만한 필드만 따로 빼내어 매핑 했습니다.
주로 주문, 주문취소, 실패에 관한 필드만 따로 뺐습니다.
이정도만 사용해도 무방할까요?(빼서 찜찜한 필드 : 결제 정보[카드사, 카드번호, 등등])

2024-08-10 12:01 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            throw new RuntimeException("iamport exception");
## 질문
여기서 발생하는 예외들은 network 관련 예외 일까요?

2024-08-11 11:22 UTC, blue000927 reviewed
피드백이 좀 많긴한데 화이팅합시다! ㅋㅋㅋ

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
그냥 ID여도 되지 않을까요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
payment_transactions 같은 테이블 하나 만들면 어떨까요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +public class OrderReceipt {
뭔가 이름에서 DTO 느낌이 나지 않는데 어떻게 생각하시나요? (처음에 도메인인줄알았네요.)

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
모두 nullable이어도 상관 없나요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/infrastructure/OrderEntity.java
> +    private String orderId;
ditto

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/infrastructure/OrderEntity.java
> +    private String paymentTxId;
ditto

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/service/OrderService.java
> +                                                                                        .billingData(orderDto.getBillingData())
네네 꼭 모든걸 정적 팩터리 메서드로 뺄 필요는 없습니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/resources/application.properties
> +payment.iamport.imp_secret=M11mpNrYutDR7gnIv8Sg6bPJ3IIoLSnKs49Z80SZxdPJoNSgQUUIjFuVB2MAKU69zPpfP0kyCODCtLRf
안 숨기면 악용당할 여지가 있습니다.
properties 단에서 ${} 와 같이 환경 변수로 선언하는 방법이 있을테니 그 방법 써보면 어떨까요?

2024-08-11 11:22 UTC, blue000927 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +                                .pwd_2Digit("")
이 부분은 모킹을 통해 테스트 진행하셔야 합니다.

2024-08-11 11:22 UTC, blue000927 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
mockito 라이브러리로 메서드 행위 자체를 모킹하셔도 되고, wiremock을 통해 일종의 PG 서버를 모킹하여 테스트 진행하셔도 됩니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
보통 외부 API와 통신하는 Client는 infrastructure 아래에 client 패키지를 파서 관리하는 편이고, `@Component`를 통해 빈으로 관리하는 편입니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
가장 쉬운 방법은 매번 access-token을 발급 받아서 처리하는 것입니다.
일단 이렇게 해 보고 다음 방법을 추후 고민해 보면 좋겠습니다.

- DB에 저장
- 메모리 캐싱 혹은 Redis 캐싱을 TTL 걸어서 수행

저장된 access-token이 만료되었다는 예외를 받으면 그때 다시 발급받아 저장하기.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static final String NICE_PG = "nice_v2.iamport01m";
이거도 바뀔 수 있는 값이어서 설정 파일로 관리하면좋겠습니다.
NICE_PG로 사용할 수 있는 채널이 몇개 더있을거예요.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +    private String pg;
고객사가 선택한 PG로 이해하시면 됩니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/service/OrderService.java
> +                            .build();
Order 같은 도메인 만큼은 생성 로직을 Order가 가져갔으면 합니다.
쓰는 쪽에서 Order를 다양하게 생성하다보면 도메인을 잘못 생성할 여지가 있다고 생각합니다.

이때는 결제 성공 상태의 Order이므로 적절히 메서드명을 정해주세요!

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
아 이 Client가 라이브러리단에서 지원을 해주는군요?
그러면 `@Bean`을 통해서 생성하는 것이 좋지 않을까요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +public class PaymentGateWay {
Gateway는 널리 쓰이는 표현은 아닌 것 같아서 Service라고 표현하는 것이 처음 코드 읽는 입장에서 오해가 없을듯합니다!

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            billingKey = fetchBillingKey(paymentDataDto);
상점은 타임딜 서비스로 이해하시면 됩니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            throw new RuntimeException("iamport exception");
이런건 보통 내부 예외로 처리하는 편입니다.
로깅은 해야 하므로 IamportException을 하나 만들어서 생성자로 message, throwable을 받고
GlobalExceptionHandler에서 message는 적당히 애매하게 전달하고 내부에서는 throwable로 로깅합니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +        }
넵 일단 이정도로 하셔도 됩니다. (paid, cancelled 등은 enum으로 선언해도 좋을듯)

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +        String billingKey = iamportClient.postBillingCustomer(UUID.randomUUID().toString(), BillingData.toBillingCustomerData(billingData))
단순히 UUID로 표현하기보다는 IDUtil 클래스 하나 만들어서 billingKeyId를 만드는 메서드를 정의하면 좋겠습니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/BillingKeyMapper.java
> +    @Insert("INSERT INTO billing_keys_table (login_id, billing_key) VALUES (#{loginId}, #{billingKey})")
BillingKeyEntity는 어디있나요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +    public static PaymentResult from(Payment iamportPayment) {
네네 원래 필요한거만 추려서 합니다.

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +    public static PaymentResult from(Payment iamportPayment) {
찜찜해도 당장 필요없으면 매핑하지 않는 것이 원칙입니다!

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
각각 그렇게 매핑해도 괜찮을까요?

2024-08-11 11:22 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +public class BillingData {
도메인이 맞을까요?
사실상 포트원 API에 매핑하기 위한 객체로 보입니다.

이럴 때는 보통 다음과 같은 전략을 취합니다.

1. 외부 API에 매핑되는 DTO 하나만 쓴다.
2. 외부 API에 매핑되는 DTO와 내부적으로 쓰는 Domain을 쓴다.

2번의 경우 Domain은 우리 용어로 풀이하고, DTO는 외부 API에서 쓰는 용어를 그대로 씁니다.

2024-08-11 20:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
payment_results_table을 사용하고 있는데(아임포트 결제 결과 저장 테이블) 말씀하신 payment_transactions는 다른 용도의 테이블 일까요?

2024-08-11 20:55 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +public class OrderReceipt {
앗 실수 입니다. 바로 수정 하겠습니다.
보통 ~Dto라고만 쓰나요? 아니면 Request, Response를 붙여 용도를 명확히 하나요?

2024-08-11 20:59 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
OrderReceiptDto처럼 외부로 나가는(조회용) 객체는 필드 null 체크를 해야하나요?
여기서 가장 중요한 id(orderId)는 fetch 메서드로 없으면 예외를 반환 하겠지만, seller나 buyer 등은 없을 수도 있다고 생각 되어서요.(중간에 탈퇴같은 경우?)

2024-08-11 21:13 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
id(orderId)처럼 유니크한 값이 보장된다면 DB에서 id(auto_increment)를 사용 안해도 될까요?

2024-08-11 21:19 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/BillingKeyMapper.java
> +    @Insert("INSERT INTO billing_keys_table (login_id, billing_key) VALUES (#{loginId}, #{billingKey})")
아 요건 loginId와 billingKey밖에 없어서
insert는 파라미터로(loginId, billingKey)로 했고,
select는 billingKey만 반환하도록 했습니다.

그렇더라도 entity나 객체를 통해 주고 받는 것이 좋을까요?

2024-08-11 21:31 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
찾아보니 wiremock도 모킹한 값을 주는 서버이군요.

그럼 이 경우에는 실제로 아임포트와 통신하는 통합 테스트와 모킹을 통한 테스트를 구분해야하는 것 이지요?

2024-08-11 21:33 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
이 부분은 하면서도 찜찜 했는데, 입의로 값의 이름을 바꾸면 다른 api를 호출할 때 문제가 생길 것 같습니다.
내부적으로 부르는건 billingKey라고 하더라도 코드 상으로는 cuntomUid라고 하는 것이 좋을까요?

2024-08-12 12:06 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
지금은 내부적으로 외부통신 Client를 사용하지 않았는데, 추후 트래픽을 감당하기 위한다면 다른 클라이언트를 사용하는 것이 좋을까요?

2024-08-12 12:10 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
네 이건 TODO 리스트에 추가해두겠습니다.

2024-08-12 12:11 UTC, corea1836 commented on src/main/resources/application.properties
> +payment.iamport.imp_secret=M11mpNrYutDR7gnIv8Sg6bPJ3IIoLSnKs49Z80SZxdPJoNSgQUUIjFuVB2MAKU69zPpfP0kyCODCtLRf
요건 찾아보고 추가 커밋 할 때 올리겠습니다.

2024-08-12 12:21 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +public class BillingData {
BillingData를 하나만 쓸거라면 BillingDataDto로 목적을 명확히 한 네이밍을 사용하고(데이터 전달 객체)
두 개를 쓸거라면 BillingDataDto(외부 데이터), BillingData(우리 용어) 로 나누되 도메인과 DTO의 용도를 명확히 하는 것이 좋다고 이해하면 될까요?

+ 이 부분이 위에서 말씀하신 costom_uid(아임포트 용어) -> billing_key(우리 용어)와 같은 맥락일까요?
지금은 PaymentResult(우리 용어)객체를 통해 외부 통신을 할 필요 없지만, PaymentResult가 가진 필드로 아임포트와 통신해야하기 때문에 PaymentResultDto를 만들어야한다. 라는 생각으로 이어졌습니다.

2024-08-14 09:58 UTC, blue000927 requested changes

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
order_id 같은 유니크 값을 PK로 했을 때 장단점이 무엇이 있을까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
(orderId, paymentTxId) 쌍으로 저장하는 PG사 결제 응답 테이블이을 생각했는데 paymentResult가 그런 역할을 하나 보군요. 
생성하는 테이블은 반드시 Entity로 표현해 주시거나 DDL로 표현해 주셔야 합니다.

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +public class OrderReceipt {
Request, Response로 명확하게 이야기할 수 있으면 그렇게 쓰고 애매하면 DTO로 가는 경우가 많습니다.
혹은 DTO 안에 내부 클래스로 정의할 때는 그런 postfix들을 제거하는 경우도 있네요~

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
해당 객체가 요청으로 쓰이는지 응답으로 쓰이는지 혼동이 있을듯합니다. 응답으로만 쓰일 경우는 상관 없을듯하네요.

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +//    }
주석 제거하기

2024-08-14 09:58 UTC, blue000927 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
테스트 코드 상에서 실제 외부 API를 호출하여 검증하면 어떠한 문제가 있을까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
우리끼리 사용하는 용어는 Presentation, Application, Domain 단에서 사용하고
외부 API에서 사용하는 용어는 Infra 단에서 사용하도록 분리하면 좋겠습니다.

우리끼리 부르는 것을 billingKey라고 하는 것은 최초 개발하는 사람들은 알겠지만, 새로운 개발자가 합류한다면 그 히스토리를 모르지 않을까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
IamportClient가 외부 통신 Client가 아닌가요? (포트원에서 제공하는)

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/BillingKeyMapper.java
> +    @Insert("INSERT INTO billing_keys_table (login_id, billing_key) VALUES (#{loginId}, #{billingKey})")
나중에 entity에 필드가 늘어나면 어떨까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +public class BillingData {
위에서 말씀드린 용어와 같은 맥락입니다!
그리고 PaymentResult, PaymentResultDto로만 보면 전자는 도메인이 맞지만 후자는 presentation에서 쓰는건가? infra에서 쓰는건가? 혼동이 있을 수 있어 보여요. 후자의 경우 단순히 Dto라고 쓰기보다는 PortoneXXX과 같이 앞단에 외부 API 네이밍을 써 주면 어떨까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/dto/PaymentDataDto.java
> +    public static AgainPaymentData toPaymentData(PaymentDataDto paymentData, final String billingKey) {
PaymentData에서 AgainPaymentData로 바꾸는 것이므로 toAgainPayment 로 명명해야하지 않을까요?

2024-08-14 09:58 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
static으로 정의한 Client와 Bean으로 정의한 Client는 트래픽 관점에서 어떠한 차이가 있는 걸까요??

2024-08-15 09:12 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
제 생각에는 세 가지 문제가 있을 수 있습니다.
1. 응답이 일관성있지 않을 수 있다. -> 테스트가 결정적이지 않다(?)
2. API 응답이 느릴 수 있다. -> 전체적인 테스트 속도를 늦추는 원인 입니다.
3. 테스트를 제어하지 못한다. -> 외부 API를 사용하면 타임아웃에 대한 부분도 고려해야할 듯 한데요. 실제 외부 API 응답을 제어하지 못하는 경우가 있어 이 케이스에 대한 테스트 코드 작성이 어렵습니다.

2024-08-15 09:13 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
그럼 실제로 외부 API가 동작하는지 안하는지 확인하는 테스트는 테스트 코드로 작성하지 않고, 인수 테스트 방식으로 하는것 일까요?

2024-08-15 09:14 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +                .orderId(iamportPayment.getMerchantUid())
아하 혼란을 초래하는군요. 다시 수정하겠습니다.

2024-08-15 09:16 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentGateWay.java
> +            throw new RuntimeException("iamport exception");
이 부분은 다른 PR에서 피드백 주신대로, 
(생산성 고려해서) 너무 디테일 하지 않고, 외부에는 모호한 메세지로 보내면서 내부적으로는 로깅 하도록 수정하겠습니다.

2024-08-15 09:35 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
혹시 질문의 의도가 auto_increment를 사용했을 때와 UUID를 생성해 DB에 pk로 넣었을 때 장단점이 맞을까요?

2024-08-15 09:43 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
네 PaymentResult는 orderId, paymentTxId를 쌍으로 저장하는 결제 응답 테이블 입니다.

결제를 위해 iamport에 AgainPaymentData 클래스를 사용하는데, 우리 서비스에서 만든 orderId(UUID)를 포함해서 보냅니다.
그리고 결과로 PaymentResult를 받는데, impUid(paymentTxId), merchantUid(orderId)를 반환 받습니다.

2024-08-15 09:45 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
말씀하신 Entity 표현 혹은 DDL로 표현이라는 것은, 지금은 PaymentResult가 domain에 있는데,
도메인이 아니므로 내부에 저장하기 위함이라면 entity 네이밍으로 표현하라는 뜻 일까요?

2024-08-15 09:46 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +public class OrderReceipt {
디토?
이것도 마찬가지로 제가 네이밍을 도메인, dto, 엔티티 명확하지 않은 경우가 있는데 사용 용도에 따라 정확하게 하겠습니다.

2024-08-15 09:47 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
응답으로 쓰는 클래스의 이름을 명확하게(~Reaponse)로 변경하겠습니다.

2024-08-15 09:59 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
아 제가 말씀드린 클라이언트가 동기식 클라이언트와 비동기식 클라이언트가 있다고 알고 있어서요.
혹시 트래픽 생각하면 그런 고려도 해야할까? 라는 의도로 드린 질문 입니다.

iamport 클라이언트의 내부 코드를 보지 못했지만, 외부 API와 통신하는 Http 클라이언트라고 생각하고 답변해보겠습니다.
static으로 정의한 클라이언트는 인스턴스 한 개 이므로 여러 요청이 폭발적으로 증가한다면, (동시성은 제어 했다고 가정) 요청은 순차적으로 수행됩니다.(트래픽도 순차적이라 늦게 응답받는 사용자도 생깁니다.)

Bean으로 정의한 클라이언트는 기본적으로 싱글톤이라면 static과 같겠지만, 빈 스코프를 조절할 수 있습니다.
request 스코프로 생성한다면, 클라이언트를 생성할 수 있습니다. 
따라서 서블릿 리퀘스트 스레드 만큼 클라이언트를 생성할 수 있어 트래픽이 동시에 처리될 수 있습니다.

2024-08-15 10:01 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/BillingKeyMapper.java
> +    @Insert("INSERT INTO billing_keys_table (login_id, billing_key) VALUES (#{loginId}, #{billingKey})")
아하! 필드가 2개인 것과 10개인 것은 단순히 파라미터로 처리하기는 어려울 것 같습니다.
수정 하겠습니다.

2024-08-15 10:12 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/BillingData.java
> +public class BillingData {
주신 피드백들 정리해 보겠습니다.
- **PaymentResult(우리 서비스) -> PaymentResultEntity** : 포트원과 결제 통신을 한 결과로 도메인이 아닌 DB에 저장하기 위함으로 목적에 맞춰 네이밍 변경
```java
public class PaymentResultEntity {
    private Long id;
    private String paymentTxId;
    private String orderId;
    private String orderName;
    ...
}
```
- **PaymentDataDto(우리 서비스) -> PortonePaymentDataRequest** : 외부 infra와 통신하기 위해 전달하는 객체로 외부 API의 이름을 prefix로 사용, infra 단으로 이동
```java
public class PortonePaymentDataRequest {
    private String orderId;
    private BigDecimal amount;
    private String customerLoginId;
    private String orderName;
    private BillingData billingData;
}
```
- **PaymentResult(우리 서비스)** : 도메인에서 사용하기 위함으로 PaymentResultEntity와 필드는 동일하지만 사용처를 명확하게 하기 위해 생성

2024-08-16 13:29 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
auto_increment가 아닌 유니크한 ID입니다! (그 안에 UUID도 있겠지만 주민등록번호 같은 것도 되겠죠? 지범님 코드 상에서는 orderId도 그럴 수 있겠네요.)

2024-08-16 13:29 UTC, blue000927 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
아뇨! 테스트 코드로 커버가 안됩니다 ㅎㅎ
외부 API가 갑자기 맛이 간다면 우리 테스트가 다 깨지게 돼서, 그런건 QA때 진행합니다.

2024-08-16 13:29 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String paymentTxId;
우리가 domain, entity 쪼개서 가기로 했으니 통일성있게 가자는 거였어요!

2024-08-16 13:29 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
아 그런 클라이언트 이야기군요. 포트원에서 제공하는 Client는 동기일 것 같긴한데 .. (이 부분은 확인해 보시죠 ㅎㅎ)
지금처럼 이 Client 자기 자신은 외부의 클래스를 의존하지 않으므로 상태가 없어서 static으로 선언해도 큰 문제는 없으나 아래 불편함이 있습니다.

- IamportClient가 도대체 뭐지? 이거 어디서 정의된거지? 엥 static 필드?? 뭐지?? 이런 생각이 들 수 있습니다. `@Bean`으로 명확히 정의하면 외부 라이브러리임을 명시할 수 있습니다.
- 테스트할 때 불편합니다. static mock은 어떻게 할 것인가?
- IamportClient라는 객체를 생성할 때 좀더 복잡한 초기화 과정이 필요하고, 여러번 호출될 가능성이 있습니다.

2024-08-17 07:28 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
생각해보니 Reponse 만으로 쓰기는 어려줘서 ~Dto로 통일하겠습니다.

2024-08-17 07:42 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
IamportClient는 통신을 위해 OkHttpClient를 사용하고 있습니다.
OkHttpClient는 동기(execute()), 비동기(enqueue()) 통신 방식을 사용하고 있으며, IamportClient는 동시 통신을 사용합니다.
또한 내부적으로 커넥션 풀(default size 5) 를 가지고 있습니다.

그래서 제가 말씀드린 내용은 문제 없어 보입니다.
JB : IamportClient가 static or bean으로 선언되어 있다면 인스턴스가 모자라 request마다 생성해줘야 할 것 같다.(X)
-> 기본적으로 커넥션 풀로 관리되고 있어, 과도한 통신 요청이 아닌 이상 이 부분은 문제가 되지 않을 것 같음.

2024-08-17 07:47 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
- Bean으로 관리하면 외부 라이브러리임을 명시할 수 있다. -> 공부한 내용이었는데, 실제로 겪어보니 다시 생각이 나는군요.
- 테스트 -> 피드백 내용 듣고 코드를 까보니, 우리 서비스 테스트 코드로 IamportClient가 제대로 동작하는지에 대한 테스트는 불필요해보입니다.(_외부 API 테스트의 단점과 더불어 IamportClient가 통신에 관해서는 테스트 완료 되었다고 가정하고 우리 서비스에 대한 테스트 케이스만 작성하면 될 것 같습니다._)
- 초기화 -> 전에 DB Config 설정할 때를 생각해보니 생성할 때 여러 설정 값을 주입해줘야 하는경우가 생각나는군요. Bean 생성으로 복잡한 초기화 과정을 도움받을 수 있을 것 같습니다.

2024-08-17 15:15 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    public static IamportClient iamportClient;
IamportClient 라이브러리에서는 매번 토큰을 발급 받는 방식이네요.

2024-08-17 15:23 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
장점은 auto_increment의 단점을 커버하는 것이 떠오릅니다.
    - auto_increment 가 ID라면 순차적으로 증가하는 값으로 인해 값 예상이 가능해 보안상 위험 요소가 있다고 알고 있습니다.
    - auto_increment는 삭제하면 중간에 값이 비기 때문에 문제가 될 수 있다.(예를들면 다른 DB로 마이그레이션 할 때 중간에 빈 값은 타겟 DB에서 다시 순차적으로 매겨질 수 있기 때문에 참조 값이라면 위험하다. : 1, 2, 5 -> 1, 2, 3)

단점은 유니크함을 보장하기 위해 데이터의 크기가 커질 수 있다는 것 입니다.

2024-08-17 15:26 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/dto/OrderReceipt.java
> +
통일된게 좋아보일 듯 해서 ~Dto로 하겠습니다.

2024-08-18 02:26 UTC, corea1836 commented
피드백 적용 입니다.

2024-08-18 02:26 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentService.java
> +public class PaymentService {
PaymentGateWay -> PaymentService 
- 클래스에 널리 쓰이는 네이밍 적용

2024-08-18 02:27 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentService.java
> +        }
결제 결과(paid, cancelled, fail) enum 적용

2024-08-18 02:29 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +    private String merchantUid;
PaymentResult(도메인, 엔티티, 테이블) 필드 수정
- paymentTxId(우리 서비스) -> impUid(아임포트)
- orderId(우리 서비스) -> merchantUid(아임포트)

우리가 쓰는 Payment 도메인에서도 아임포트의 필드와 동일한 필드를 사용하도록 변경 했습니다.
피드백 주신대로 필드명을 임의의 지점에서 변경하면, 다른 사람으로 하여금 오해를 불러 일으키고 변경 지점에 대한 명확한 기준이 없기 때문에 후에 코드 상 휴먼 에러를 일으키기 때문입니다.
하지만, Order에서는 주문 도메인에 직관적인 네이밍이 필요하다 생각되어 paymentTxId, orderId로 변경해서 적용했습니다.

2024-08-18 02:33 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/IamportApiClient.java
> +public class IamportApiClient {
PaymentService에서 Iamport와 통신 후 처리하던 부분을 infrastructure 레이어로 분리 했습니다.
이유는 역할 분리와 예외 처리를 위해서 입니다.
우리 서비스에서 사용하는 ImportException 를 적용했고, 사용자에게는 "Network Error" 라는 메세지만 보여주고, 내부적으로 로깅 합니다.
링크 : https://github.com/f-lab-edu/just-10-minutes/pull/13/files#diff-51fba5055d06b6ab4b497206571b07daf31c1c8df27ac9be8ae3fb34bd38a34eR59

2024-08-18 02:35 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Common/IDUtil.java
> +public class IDUtil {
UUID로 생성하던 아래 내용 유틸 클래스로 분리
- orderId
- customUid

2024-08-18 02:35 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +    @Value("${payment.iamport.nice_pg}")
pg 채널 설정 파일로 분리

2024-08-18 02:37 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +        }
Order에서 넘어온 PG(enum) 을 각각 맞는 채널에 매핑하기 위한 메서드 입니다.
ex. PG : NICE -> "nice_v2.iamport01m"

2024-08-18 02:39 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    public static Order from(PaymentResult paymentResult, User seller, Long buyQuantity, User buyer, Long totalPrice) {
OrderService에서 결제 후 주문 객체를 저장하기 위해 생성하던 빌더를 옮겨왔습니다.
생성자의 단점인 파라미터 실수(같은 타입일 때 휴먼 에러로 인해 잘못 매핑)가 있을 수 있어 지양하려 했지만,
4, 5개 정도는 크게 실수할 일이 없어 보였습니다.

2024-08-18 02:43 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    public static Order createCompleteOrder(PaymentResult paymentResult, User seller, Long buyQuantity, User buyer, Long totalPrice) {
OrderService에서 결제 후 주문 객체를 저장하기 위해 생성하던 빌더를 옮겨왔습니다.
생성자의 단점인 파라미터 실수(같은 타입일 때 휴먼 에러로 인해 잘못 매핑)가 있을 수 있어 지양하려 했지만,
막상 메서드로 만들어보니 4, 5개 정도는 크게 실수할 일이 없어 보였습니다.

2024-08-18 02:53 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/dto/IamportPaymentRequestDto.java
> +public class IamportPaymentRequestDto {
Iamport 서버와 통신하기 위한 객체 입니다.
피드백 주신 전략 중 외부 API와 통신하기 위한 Dto 한 개만 사용 했습니다.

각 객체의 사용처를 정리하면 아래와 같습니다.
- IamportPaymentRequestDto : Iamport 서버와 통신하기 위한 객체
- PaymentResult : Iamport서버와 통신 후 반환한 Payment객체를 우리 서비스에서 사용하기 위해 매핑한 도메인 클래스
- PaymentResultEntity : DB에 저장하기 위해 매핑한 엔티티 클래스

2024-08-18 03:00 UTC, corea1836 commented on src/test/java/com/flab/just_10_minutes/Order/OrderIntegrationTest.java
> +    public void order_성공() throws Exception {
아하 실제로는 테스트 코드와 QA의 검증 내용은 다른 것으로 봐야하는군요.
말씀하신대로 테스트 코드에서 외부 API가 맛이 가면 테스트 코드의 의미가 없어보이므로 모킹해야하는 것이 어떤 의미인지 이해가 갑니다.

2024-08-18 03:04 UTC, corea1836 commented
## 핑퐁중이던 대화

- 유니크 아이디가 PK가 되었을 때 장단점
링크 : https://github.com/f-lab-edu/just-10-minutes/pull/13#discussion_r1712960520
- IamportClient를 static -> bean
https://github.com/f-lab-edu/just-10-minutes/pull/13#discussion_r1712962614

2024-08-18 03:05 UTC, corea1836 commented
## 아직 해결하지 못한 내용

- IamportClient라이브러리는 엔드 포인트가 포트원 으로 고정되어 있어 모킹이 어려움(슬랙에 올린 내용)

2024-08-19 14:25 UTC, blue000927 reviewed
## 질문
IamportClient라이브러리는 엔드 포인트가 포트원 으로 고정되어 있어 모킹이 어려움(슬랙에 올린 내용)

## 답변
IamportClient 자체를 모킹하면 안될까요?

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/service/OrderService.java
> +        Long productOriginalPrice = 10000L;
테스트용인가요?

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
MySQL 클러스터링 인덱스는 어떻게 동작할까요~?

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/PaymentResult.java
> +    private String merchantUid;
좋아요 이건 괜찮네요!

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/Status.java
> +public enum Status {
그냥 Status라고만 하면 좀 헷갈리지 않을까요? ㅎㅎ

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentService.java
> +        if (paymentResult.getStatus().equals(Status.PAID)) {
enum은 == 으로 비교해도 됩니다. 왜 그럴까요?

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/dto/BillingRequestDto.java
> +public class BillingRequestDto {
혼선을 방지하기 위해 Iamport에서 쓰이는 객체는 앞에 Iamport를 붙여주면 좋을것같습니다.

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/CustomUidEntity.java
> +public class CustomUidEntity {
흠 테이블 이름이 id인 것은 좀 어색하군요. 그리고 Custom이 아니고 Customer아닌가요?
제 생각에는 테이블 이름을 customer 정도로 가도 충분해 보일 듯싶네요. (customer_uid를 저장하기 위해)
아니면 명시적으로 billingKey 워딩이 들어가도 될거같아요.

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/PaymentResultEntity.java
> +    private Date cancelledAt;
Date 대신 LocalDateTime 으로 쓰면 어떨까요

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +        }
1. Config 파일에 있는 것이 맞을까요?
2. 이 메서드를 호출하기 위해 매번 Config 클래스를 주입 받으면 어떤 문제가 있을까요?

2024-08-19 14:25 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Handler/GlobalExceptionHandler.java
> +    }
Good!

2024-08-19 14:25 UTC, blue000927 commented on src/main/resources/application.properties
> +payment.iamport.nice_pg=nice_v2.iamport01m
이거 이렇게 보여주시면...!!

2024-08-22 14:33 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/gateway/PaymentService.java
> +        if (paymentResult.getStatus().equals(Status.PAID)) {
enum은 static과 final의 성격을 갖습니다.
실제로 static, final은 아니지만, 런타임 때 JVM이 해당 enum 클래스를 생성하고 싱글톤을 보장 합니다.
따라서 enum 의 멤버 변수는 일관된 메모리 주소를 보장하기 때문에 == 비교가 가능 합니다.

2024-08-23 00:21 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Iamport/IamportConfig.java
> +                .messageConverters(converters -> converters.add(new MappingJackson2HttpMessageConverter(new ObjectMapper())))
전 이 부분이 request 자바 객체를 json 형식으로 파싱 해주는 부분으로 알고 있었는데, 코드를 없애도 요청은 잘 가네요.
직렬화 하는 내장 객체가 따로 있는 것 일까요?

2024-08-23 00:23 UTC, corea1836 commented
RestClient로 Iamport 라이브러리의 통신 객체를 전환 했습니다.

2024-08-23 00:51 UTC, corea1836 commented
라이브러리로 제공되던 IamportClient(OkHttp 사용)을 RestClient로 교체 했습니다.

IamportApiClient 클래스를 보시면 빡구현을 했던터라 공통화 시도를 해봤습니다.
인터페이스로 추상화, 공통 메서드로 전환(제네릭 사용) 하려 했으나 반환 타입의 타입 레페런스가 잘 안되어 이대로 올렸습니다.(공통화는 시간날 때 해봐야겠습니다.)

또한, 설정 값들을 인터넷에서 보고 했는데 필요한 설정인지 아닌지 판단이 잘 안되는데 하나씩 검증 해보는건 TODO 로 미루고 되는 코드 기반으로 올렸습니다.
( RestClient를 생성할 때 messageConverter 를 설정 on/off 해보았는데 모두 동작하네요.ㅎㅎ;)

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Iamport/IamportConfig.java
> +                .messageConverters(converters -> converters.add(new MappingJackson2HttpMessageConverter(new ObjectMapper())))
전 이 부분이 request 자바 객체를 json 형식으로 파싱 해주는 부분으로 알고 있었는데, 코드를 없애도 요청은 잘 가네요.
직렬화 하는 내장 객체가 따로 있는 것 일까요?

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Iamport/IamportConfig.java
> +//    }
이 부분은 시도했다가 실패한 부분에 대해서 입니다.
원래는 아래 코드처럼 인터페이스와 연결해 RestClient 사용 부분을 추상화 하려 했으나, RequestHeader설정이 잘 안되어 구체 클래스로 만들었습니다.
```java
public interface IamportClient {

    @PostExchange(value = "/users/getToken")
    IamportResponse<IamportAccessToken> token(@RequestBody IamportAuthData auth);
    ...
}
```

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/IamportApiClient.java
> +        }
iamport 통신 결과는 http status는 통신 오류가 아닌 이상 200 OK 으로 오고
IamportResponse 객체의 code 필드에 -1, message에 상태 코드를 첨부해서 반환합니다.
ex.
```json
{
    "code": -1,
    "message": "카드정보 인증 및 빌키 발급에 실패하였습니다. [400]method.card.credential.birthOrBusinessRegistrationNumber violates the rule LENGTH_ONE_OF([6,10]) (value=\"000000\")",
    "response": null
}
```

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/request/IamportAgainPaymentData.java
> +public class IamportAgainPaymentData {
Iamport 빌링 API 결제 요청 객체 입니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/request/IamportAuthData.java
> +public class IamportAuthData {
Iamport accesstoken 발급 요청 객체 입니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/request/IamportBillingCustomerData.java
> +public class IamportBillingCustomerData {
Iamport billingKey 발급 요청 객체 입니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/response/IamportAccessToken.java
> +public class IamportAccessToken {
Iamport accessToekn 반환 객체 입니다.
accessToken 필드를 이후 요청의 헤더(Authorization) 에 넣어야 Iamport와 통신이 가능 합니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/response/IamportBillingCustomer.java
> +public class IamportBillingCustomer {
Iamport BillingKey 발급 반환 객체 입니다.
여기서 customer_uid를 제외하고는 사실 필요한지 의문 입니다만 일단 중요 정보라 생각해 받고, 그 이외 정보는 JsonIgnore로 매핑하지 않았습니다.
(나머지는 카드 정보라 우리 서비스가 이 정보를 저장할지 여부는 비지니스에 따라 달라질 것 같습니다.)

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/response/IamportPayment.java
> +public class IamportPayment {
Iamport 결제 반환 객체 입니다.
지금은 결제, 취소, 실패에 대한 내용만 매핑합니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/response/IamportResponse.java
> +public class IamportResponse<T> {
Iamport 반환 세부 정보ex. IamportPayment를 감싼 객체 입니다.
Iamport는 IamportResponse 객체로 T response객체를 감싸 응답을 반환 합니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/dto/BillingRequestDto.java
> +public class BillingRequestDto {
Iamport와 통신을 위한 객체는 모두 prefix(Iamport~) 붙였습니다.
Payment/dto의 두 객체(BillingRequeset, PaymentRequest)는 우리 서비스에서 사용하는 객체라 prefix 사용하지 않았습니다.

2024-08-23 00:52 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Exception/Iamport/IamportException.java
> +        super(message, new Throwable(cause));
Iamport 와 통신 중 발생한 예외 처리 방법을 변경 했습니다.
원래는 Iamport와 통신 후 결과는 IamportResponse 클래스의 code, message에 담겨 오기 때문에
ex.
```json
{
    "code": -1,
    "message": "Unauthorized",
    "response": null
}
```
받은 예외를 처리하기 위해 메세지 발생 장소 IamportApiClient에서 메세지를 넘겨주고 여기서 Throwable로 감싸 예외를 생성 합니다.
(GlobalHandler에서 처리하기 위해)

2024-08-23 00:53 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/CustomUidEntity.java
> +public class CustomUidEntity {
BillingKeyEntity로 변경 했습니다.
BillingKey 객체 안에 customerUid와 loginId 가 있는 것이 더 자연스러웠습니다.

2024-08-23 00:54 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/domain/Status.java
> +public enum Status {
PaymentResultStatus라고 명확한 명칭으로 변경 했습니다.

2024-08-23 00:55 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/service/OrderService.java
> +        Long productOriginalPrice = 10000L;
이 부분은 아직 Product가 함쳐지지 않아 가격을 대신할 것을 넣었습니다.
지우겠습니다.

2024-08-23 02:18 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +        }
이 부분은 제가 의도한 방향과 달라서 상황 설명을 드리겠습니다.
iamport pg사 채널은 변경될 수 있기 때문에 프로퍼티 파일에서 관리 중 입니다.
(제가 알기로는 프로퍼티 파일은 런타인 중에도 변경 가능하다는 걸로 알고 있습니다.)

반면, 사용자 요청에 있는 PG는 enum으로 관리 중 입니다.(잘못된 요청을 막기 위해)
그래서 자바 enum인 PG가 config에서 정확한 채널명을 받는 요상한(?) 방식으로 짜였습니다.(1의 답변)

enum 매핑을 위해 Config 클래스를 호출 마다 주입 받으면 강한 결합이 생깁니다.
IamportConfig는 다른 도메인과 결합이 생기지 않도록 Payment 도메인에서만 주입하고 있지만, 다른 도메인과 결합이 생기지 않는다고 보장할 수 없기 때문에 다른 방법이 필요해 보입니다.

저는 아래 두 방법을 생각 해봤는데요.
1. static Map으로 만들어서 postConstructor로 생성
2. enum에 lable 필드를 만들어 매핑

이 두가지는 새로 빌드를 해야하는 경우가 생겨 기존 방식을 유지 했습니다.

서비스가 돌아가는 도중에 iamport 채널 명을 변경해야할 경우가 생길까요?

2024-08-23 02:18 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Util/Config/IamportConfig.java
> +        }
그리고 Config 클래스에 의존이 많이 발생하면 강한 결합이 생기는데 구체적으로 어떤 문제가 연계 될지는 잘 모르겠습니다.

2024-08-23 02:27 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
아하 주신 키워드로 다시 고민 해봤습니다.
MySQL 클러스터링 인덱스는 InnoDB에서 PK를 통해 생성하는 인덱스이고, B- 트리 구조라 항상 정렬되어있다는 특징이 있습니다.
따라서 삽입, 삭제에는 재정렬 비용이 발생하는데, java의 Util.UUID 클래스는 버전4 UUID(무작위 UUID) 이기 때문에 삽입, 삭제 시 정렬 비용이 필요합니다.
따라서 연속됨을 어느정도 보장할 수 있는 방법이 필요한데,
- 버전1 UUID(TimeStamp, Mac) 기반으로 생성하는 UUID
- MySQL 채번을 이용한 함수

가 필요하다고 생각 됩니다.
(저는 분산 서버 환경이더라도 TimeStamp와 Mac 주소라면 겹칠일이 거의 없다고 생각되는데 실무에서는 어떤 방식을 사용하나요?)

2024-08-23 02:29 UTC, corea1836 commented
### 미해결
- UUID 변경
- properties에 민감한 변수 지우기
- Date -> LocalDateTime : 이유 정확히 알고 지우기(공부중)

2024-08-23 15:04 UTC, blue000927 approved these changes
PR이 너무 루즈해 지는 느낌이 있어서 (conversation 개수 너무 많기도 하고) 일단 반영할만큼 반영하시고 나머지 이슈로 싹다 TODO로 빼서 작업해주세요. 현재 미해결된 내용이 엄청 급한건 아니라서 다음 스텝 잘 진행해주시면 좋겠습니다 :)

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/dto/BillingRequestDto.java
> +public class BillingRequestDto {
Request가 dto 하위 느낌으로 쓰는 편이라 Request만 써도 될거같아요

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/CustomerUidDao.java
> +public class CustomerUidDao {
BillingKeyDao

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/CustomerUidDao.java
> +    private final BillingKeyMapper customUidMapper;
billingKeyMapper

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/IamportApiClient.java
> +        }
code가 -1이면 예외 던지는 코드를 따로 메서드로 빼 보면 어떨까요?

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/request/IamportAgainPaymentData.java
> +    private String buyerName;
이거 클래스 레벨에 @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class) 붙이면 한꺼번에 snake_case 매핑해줘요

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/PaymentResultDao.java
> +public class PaymentResultDao {
보통 entity 패키지, repo 패키지 만들고 repo 패키지 안에 mapper, dao 패키지를 두거나
entity 패키지, mapper 패키지, dao 패키지 분리해서 두는데 한번 원하시는 방향으로 모아보면 어떨까요?

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Iamport/IamportConfig.java
> +//    }
흠 일단 TODO로 빼보시죠. 저도 고민해볼게요

2024-08-23 15:04 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Util/Iamport/IamportConfig.java
> +                .messageConverters(converters -> converters.add(new MappingJackson2HttpMessageConverter(new ObjectMapper())))
```java
/**
	 * Create a new {@code RestClient} based on the configuration of the
	 * given {@code RestTemplate}. The returned builder is configured with the
	 * template's
	 * <ul>
	 * <li>{@link RestTemplate#getRequestFactory() ClientHttpRequestFactory},</li>
	 * <li>{@link RestTemplate#getMessageConverters() HttpMessageConverters},</li>
	 * <li>{@link RestTemplate#getInterceptors() ClientHttpRequestInterceptors},</li>
	 * <li>{@link RestTemplate#getClientHttpRequestInitializers() ClientHttpRequestInitializers},</li>
	 * <li>{@link RestTemplate#getUriTemplateHandler() UriBuilderFactory}, and</li>
	 * <li>{@linkplain RestTemplate#getErrorHandler() error handler}.</li>
	 * </ul>
	 * @param restTemplate the rest template to base the returned client's
	 * configuration on
	 * @return a {@code RestClient} initialized with the {@code restTemplate}'s
	 * configuration
	 */
	static RestClient create(RestTemplate restTemplate) {
		return new DefaultRestClientBuilder(restTemplate).build();
	}
```

문서보니 디폴트로 HttpMessageConverters 설정되어있다고합니다.

2024-08-23 15:04 UTC, blue000927 commented on src/main/resources/application.properties
> +payment.iamport.nice_pg=nice_v2.iamport01m
안 보이게 환경 변수로 설정해주세요.

2024-08-23 15:06 UTC, blue000927 commented on src/main/java/com/flab/just_10_minutes/Order/domain/Order.java
> +    private String orderId;
보통 UUID 써서 안 겹치게 하는편이에요. 정답은 없습니다!

2024-08-25 04:13 UTC, corea1836 commented on src/main/java/com/flab/just_10_minutes/Payment/infrastructure/Iamport/request/IamportAgainPaymentData.java
> +    private String buyerName;
와! 꿀팁 감사합니다!

2024-08-25 04:25 UTC, corea1836 commented
TODO 리스트 정리 후 PR 닫겠습니다.

## 다음 PR로 넘길 TODO 리스트
- **프로퍼티 민감한 변수 빼기(중요)**
- IamportClient code == -1일 때 메서드 빼기
- Iamport 객체 클래스 레벨에 스네이크 케이스 전략 더하기
- entity, dao, mapper 계층 분리
- CustomerUid -> BillingKey 
- RequestDto -> Request
- Date -> LocalDateTime

## 이후 시간 날 때 작업할 TODO 리스트
- RestClient 추상화
- 테스트 코드 작성
- wiremock 테스트 코드 작성

2024-08-25 06:22 UTC, merged